name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.13

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Run Cypress tests
      run: bun run test:e2e
      continue-on-error: false
