name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.13

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Run Cypress tests
      run: bun run test:e2e
      continue-on-error: false

    - name: Configure AWS credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Sync S3 Bucket
      if: success()
      run: aws s3 sync dist/ ${{ secrets.S3_BUCKET }} --delete
    - name: Clear Cloudfront cache
      if: success()
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
